apiVersion: v1
kind: ConfigMap
metadata:
  name: jt-config
  namespace: jt-namespace
data:
  MYSQL_ENDPOINT: "mysql:3306"
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true