# https://docs.aws.amazon.com/ko_kr/eks/latest/userguide/specify-service-account-role.html
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: demo-20210924
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::239234376445:role/eksctl-kb-prd-callbot-eks-addon-iamserviceac-Role1-F58M8XISA3S6



# {
#   "Version": "2012-10-17",
#   "Statement": [
#     {
#       "Effect": "Allow",
#       "Principal": {
#         "Service": "eks.amazonaws.com"
#       },
#       "Action": "sts:AssumeRole"
#     }
#   ]
# }