---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-20210924
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
  namespace: demo-20210924
spec:
  selector:
    matchLabels:
      app: demo-server
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0       # how many pods we can add at a time
      maxUnavailable: 25  # maxUnavailable define how many pods can be unavailable during the rolling update    
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
      - name: demo-server
        image: 239234376445.dkr.ecr.ap-northeast-2.amazonaws.com/demo:44
        ports:
        - containerPort: 80
      terminationGracePeriodSeconds: 30
      env:
        # Define the environment variable
        - name: MYSQL_ENDPOINT # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: demo-config           # The ConfigMap this value comes from.
              key: MYSQL_ENDPOINT # The key to fetch.
...
