---
apiVersion: v1
kind: Namespace
metadata:
  name: test-20210914
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server
  namespace: test-20210914
spec:
  selector:
    matchLabels:
      app: tcp-server
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0       # how many pods we can add at a time
      maxUnavailable: 25  # maxUnavailable define how many pods can be unavailable during the rolling update    
  template:
    metadata:
      labels:
        app: tcp-server
    spec:
      containers:
      - name: tcp-server
        image: 239234376445.dkr.ecr.ap-northeast-2.amazonaws.com/tcp-server:v2
        ports:
        - containerPort: 80
      terminationGracePeriodSeconds: 30
...
