---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syha-card
  namespace: logging-test
spec:
  selector:
    matchLabels:
      app: syha-card
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0       # how many pods we can add at a time
      maxUnavailable: 1  # maxUnavailable define how many pods can be unavailable during the rolling update    
  template:
    metadata:
      labels:
        app: syha-card
    spec:
      nodeSelector:
        app: kb-prd-ng-adm
#      serviceAccountName: my-serviceaccount
#      serviceAccount: my-serviceaccount
      containers:
      - name: syha-card
        image: 239234376445.dkr.ecr.ap-northeast-2.amazonaws.com/demo:card
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health_check.html
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
#        lifecycle:
#          preStop:
#            exec:
#              command:  ["/bin/bash", "-c", "/preStop.sh"]
      terminationGracePeriodSeconds: 300
...
