---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syha-ip
  namespace: demo-20210924
spec:
  selector:
    matchLabels:
      app: syha-ip
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%       # how many pods we can add at a time
      maxUnavailable: 25%  # maxUnavailable define how many pods can be unavailable during the rolling update    
  template:
    metadata:
      labels:
        app: syha-ip
    spec:
      nodeSelector:
        app: kb-prd-ng-adm
      containers:
      - name: syha-ip
        image: 239234376445.dkr.ecr.ap-northeast-2.amazonaws.com/demo:49
        ports:
        - containerPort: 80
      terminationGracePeriodSeconds: 300
...
